name: Ejecutar Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Corre el bot cada hora

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install websocket-client flask
        
    - name: Run the bot
      run: |
        python server.py
      
